void showHelp(char *argv[])
{
    std::string inspirobot = std::string(argv[0]);
    std::string options = "[-h] [--file {image,audio}]";
    std::string usage = "usage: " + inspirobot + " " + options;
    std::string description =
        "download inspirational images generated by "
        "https://inspirobot.me/";
    // argument - sub-command - description
    std::string positionalArgs =
        "positional arguments:\n"
        "--file\t{image,audio}\tfetch generated image or audio";
    std::string optionallArgs =
        "optional arguments:\n"
        "";

    std::cout << usage << "\n"
              << endl;
    std::cout << description << "\n"
              << endl;
    std::cout << positionalArgs << "\n"
              << endl;
    std::cout << optionallArgs << "\n"
              << endl;
}

char *getCmdOption(char **begin, char **end, const std::string &option)
{
    char **itr = std::find(begin, end, option);
    if (itr != end && ++itr != end)
    {
        return *itr;
    }
    return 0;
}

bool cmdOptionExists(char **begin, char **end, const std::string &option)
{
    return std::find(begin, end, option) != end;
}
